apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: rookout/microservices-demo-frontend:1.0.322
        ports:
        - containerPort: 80
      imagePullPolicy: Always